### PR TITLE
Fixed typos, improved wording

### PR DESCRIPTION
**Pull request by urbalazs**
Hi @UdoBretz 
I translated these stats into Hungarian, and I found some typos during translation. I also improved wording to be consistent with the other descriptions. This PR contains these changes.

But where do I put the Hungarian stats?
My suggestion is to create subfolders for each languages, like `var/stats/en` for English, `var/stats/hu` for Hungarian, etc. Then it need to change the packagesetup, that only those stats will be installed, which are matched for the locale (e. g. if an admin uses Hungarian frontend, then only Hungarian stats will be installed).

### CODE REVIEW

**Comment by UdoBretz** [comment]
Hello @urbalazs,

thanks, I merged your pull request. I will discuss the question where to put the translated stats with @mgruner next week, and I will keep this PR opened as a reminder.

Best regards,
Udo

**Comment by urbalazs** [comment]
Hi @UdoBretz and @mgruner 
Maybe the using of attribute `Translatable="1"` would be the best solution with elements `Description` and `Title`.
If we have separate files for each languages, then it is hard to maintain if something need to change, because it have to change in every .xml files. And on the other hand only installing stats of a particular language makes hard to use them in such an OTRS installation, on which work multiple agents from different countries. They would like to use stats in his/her default language. Making stats translatable can help them.
I don't know, if the current OTRS framework can translate the titles and descriptions of stats in every screens that they are shown. It has to investigate.

**Comment by urbalazs** [comment]
Hi @UdoBretz and @mgruner 
Could you discuss the question where to put the translated stats?

**Comment by urbalazs** [comment]
Hi @UdoBretz and @mgruner 
Any news?

**Comment by UdoBretz** [comment]
@mgruner, can we discuss this on monday?

**Comment by mgruner** [comment]
@UdoBretz sure, just contact me.

**Comment by urbalazs** [comment]
Hi @UdoBretz and @mgruner
Any news?

**Comment by urbalazs** [comment]
Hi @UdoBretz and @mgruner
Any news about this? I translated the stats into Hungarian. The original question was: where do I put the Hungarian stats?

**Comment by urbalazs** [comment]
The pull request was merged. I will create a separate pull request for the Hungarian stats.

**Pull request closed without merging**
